### ISSUE TITLE
`benchmarkpkg(pathof` not working

### ISSUE THREAD

**Issue by Wikunia** [JuliaCI/PkgBenchmark.jl#111]
In the documentation I find `pathof(module)` everywhere but I think you mean `pkgdir` instead at least that one works and `pathof` doesn't. 
Generally it would be nice if `benchmarkpkg(module)` would work :smile:

**Comment by Wikunia** [comment]
Oh okay `benchmarkpkg("module")` works which is fine but `pathof` doesn't for me in Julia v1.4

**Comment by omus** [comment]
I also ran into this. I think it's just a documentation error

**Comment by omus** [comment]
> Generally it would be nice if `benchmarkpkg(module)` would work

I agree. I'll also make a PR for that
