### ISSUE TITLE
Benchmark failing with 3D images

### ISSUE THREAD

**Issue by juliohm** [JuliaCI/PkgBenchmark.jl#13]
I don't know what is happening, but please consider this code:

```julia
using ImageQuilting
using GeoStatsImages
using PkgBenchmark

srand(2017)

TI = rand(50, 50, 50)
iqsim(TI, 10, 10, 10, size(TI)...) # warm up

@benchgroup "2D simulation" ["iqsim"] begin
  for TIname in ["Strebelle", "StoneWall"]
    TI = training_image(TIname)
    @bench TIname iqsim(TI, 30, 30, 1, size(TI)..., nreal=3)
  end
end

@benchgroup "3D simulation" ["iqsim"] begin
  TI = training_image("StanfordV")
  @bench "StanfordV" iqsim(TI, 30, 30, 10, size(TI)...)
end
```

It works if I comment out the `@benchgroup "3D simulation"`, what is the reason it is failing? The command is correct and runs perfectly without the `@bench` macro in front.

You can try it for yourself in the package itself: https://github.com/juliohm/ImageQuilting.jl

Please let me know how I can fix this issue.

**Comment by juliohm** [comment]
I have updated the issue, can anyone help debug?

**Comment by omus** [comment]
cc: @shashi

**Comment by juliohm** [comment]
I tried it again after a long time without looking into the benchmarks, and it is now resulting in a different issue. The code is not hanging anymore, which is good news. Now the error message looks like the following for the 3D case:

>Creating benchmark tuning file /home/juliohm/.julia/v0.5/ImageQuilting/benchmark/.tune.jld
ERROR: BoundsError: attempt to access 105×155×1 Array{Float64,3} at index [1:100,1:130,1:30]
 in throw_boundserror(::Array{Float64,3}, ::Tuple{UnitRange{Int64},UnitRange{Int64},UnitRange{Int64}}) at ./abstractarray.jl:363
 in checkbounds at ./abstractarray.jl:292 [inlined]
 in view at ./subarray.jl:64 [inlined]
 in #iqsim#14(::Float64, ::Float64, ::Float64, ::Void, ::Void, ::Float64, ::Symbol, ::Symbol, ::Bool, ::Int64, ::Int64, ::Bool, ::Bool, ::Bool, ::ImageQuilting.#iqsim, ::Array{Float64,3}, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64) at /home/juliohm/.julia/v0.5/ImageQuilting/src/iqsim.jl:381
 in (::ImageQuilting.#kw##iqsim)(::Array{Any,1}, ::ImageQuilting.#iqsim, ::Array{Float64,3}, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64) at ./<missing>:0
 in ##core#326() at /home/juliohm/.julia/v0.5/BenchmarkTools/src/execution.jl:290
 in ##sample#327(::BenchmarkTools.Parameters) at /home/juliohm/.julia/v0.5/BenchmarkTools/src/execution.jl:296
 in #_run#2(::Bool, ::String, ::Array{Any,1}, ::Function, ::BenchmarkTools.Benchmark{Symbol("##benchmark#325")}, ::BenchmarkTools.Parameters) at /home/juliohm/.julia/v0.5/BenchmarkTools/src/execution.jl:324
 in (::BenchmarkTools.#kw##_run)(::Array{Any,1}, ::BenchmarkTools.#_run, ::BenchmarkTools.Benchmark{Symbol("##benchmark#325")}, ::BenchmarkTools.Parameters) at ./<missing>:0
 in anonymous at ./<missing>:?
 in #run_result#16(::Array{Any,1}, ::Function, ::BenchmarkTools.Benchmark{Symbol("##benchmark#325")}, ::BenchmarkTools.Parameters) at /home/juliohm/.julia/v0.5/BenchmarkTools/src/execution.jl:40
 in (::BenchmarkTools.#kw##run_result)(::Array{Any,1}, ::BenchmarkTools.#run_result, ::BenchmarkTools.Benchmark{Symbol("##benchmark#325")}, ::BenchmarkTools.Parameters) at ./<missing>:0
 in #run#17(::Array{Any,1}, ::Function, ::BenchmarkTools.Benchmark{Symbol("##benchmark#325")}, ::BenchmarkTools.Parameters) at /home/juliohm/.julia/v0.5/BenchmarkTools/src/execution.jl:43
 in (::Base.#kw##run)(::Array{Any,1}, ::Base.#run, ::BenchmarkTools.Benchmark{Symbol("##benchmark#325")}, ::BenchmarkTools.Parameters) at ./<missing>:0
 in #tune!#22(::Bool, ::String, ::Array{Any,1}, ::Function, ::BenchmarkTools.Benchmark{Symbol("##benchmark#325")}, ::BenchmarkTools.Parameters) at /home/juliohm/.julia/v0.5/BenchmarkTools/src/execution.jl:130
 in (::BenchmarkTools.#kw##tune!)(::Array{Any,1}, ::BenchmarkTools.#tune!, ::BenchmarkTools.Benchmark{Symbol("##benchmark#325")}, ::BenchmarkTools.Parameters) at ./<missing>:0 (repeats 2 times)
 in #tune!#21(::Bool, ::String, ::Array{Any,1}, ::Function, ::BenchmarkTools.BenchmarkGroup) at /home/juliohm/.julia/v0.5/BenchmarkTools/src/execution.jl:122
 in (::BenchmarkTools.#kw##tune!)(::Array{Any,1}, ::BenchmarkTools.#tune!, ::BenchmarkTools.BenchmarkGroup) at ./<missing>:0
 in #tune!#21(::Bool, ::String, ::Array{Any,1}, ::Function, ::BenchmarkTools.BenchmarkGroup) at /home/juliohm/.julia/v0.5/BenchmarkTools/src/execution.jl:122
 in cached_tune(::String, ::BenchmarkTools.BenchmarkGroup, ::Bool) at /home/juliohm/.julia/v0.5/PkgBenchmark/src/runbenchmark.jl:147
 in runbenchmark_local(::String, ::String, ::String, ::Bool) at /home/juliohm/.julia/v0.5/PkgBenchmark/src/runbenchmark.jl:29
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
INFO: No packages to install, update or remove
ERROR: LoadError: unlink: no such file or directory (ENOENT)
 in uv_error at ./libuv.jl:68 [inlined]
 in unlink(::String) at ./file.jl:382
 in #rm#7(::Bool, ::Bool, ::Function, ::String) at ./file.jl:107
 in withtemp(::PkgBenchmark.##11#15{String,String,Bool}, ::String) at /home/juliohm/.julia/v0.5/PkgBenchmark/src/runbenchmark.jl:39
 in with_reqs(::PkgBenchmark.##10#14{String,String,Bool}, ::Dict{String,Base.Pkg.Types.VersionSet}, ::PkgBenchmark.##12#16) at /home/juliohm/.julia/v0.5/PkgBenchmark/src/util.jl:21
 in with_reqs(::PkgBenchmark.##10#14{String,String,Bool}, ::String, ::Function) at /home/juliohm/.julia/v0.5/PkgBenchmark/src/util.jl:10
 in (::PkgBenchmark.#do_benchmark#13{String,String,String,String,Bool,Bool,Bool,String})() at /home/juliohm/.julia/v0.5/PkgBenchmark/src/runbenchmark.jl:66
 in #benchmarkpkg#9(::String, ::String, ::String, ::String, ::Bool, ::Bool, ::Bool, ::Bool, ::PkgBenchmark.#benchmarkpkg, ::String, ::Void) at /home/juliohm/.julia/v0.5/PkgBenchmark/src/runbenchmark.jl:106
 in benchmarkpkg(::String) at /home/juliohm/.julia/v0.5/PkgBenchmark/src/runbenchmark.jl:63
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/juliohm/.julia/v0.5/ImageQuilting/benchmark/runbench.jl, in expression starting on line 3

**Comment by juliohm** [comment]
Such an awesome package, but almost no support :disappointed:

**Comment by shashi** [comment]
```julia
@benchgroup "2D simulation" ["iqsim"] begin
  for TIname in ["Strebelle", "StoneWall"]
    TI = training_image(TIname)
    @bench TIname iqsim($TI, 30, 30, 1, size($TI)..., nreal=3)
  end
end

@benchgroup "3D simulation" ["iqsim"] begin
  TI = training_image("StanfordV")
  @bench "StanfordV" iqsim($TI, 30, 30, 10, size($TI)...)
end
```
does the trick... It seems it was using the TI defined outside all along. I'll see if I can make a fix for this in the package.

**Comment by juliohm** [comment]
@shashi that would be great, this is the only issue that is holding me from adopting benchmarks in all my packages.
