### ISSUE TITLE
Link to BenchmarkTools in "Defining a benchmark suite" is broken

### ISSUE THREAD

**Issue by Seelengrab** [JuliaCI/PkgBenchmark.jl#140]
The link pointing to BenchmarkTools' doc about BenchmarkGroups in here is broken/404s:

https://juliaci.github.io/PkgBenchmark.jl/stable/define_benchmarks/

**Comment by KristofferC** [comment]
Perhaps you can make a PR to fix it.

**Comment by Seelengrab** [comment]
Well seems like this has already been fixed in https://github.com/JuliaCI/PkgBenchmark.jl/pull/134, which I only noticed because I was trying to figure out whether I can run this easily in CI or not and noticed that that PR was the last commit to this repo. There just hasn't been a release since then.
