### ISSUE TITLE
Feat: can I jump tuning stage?

### ISSUE THREAD

**Issue by skyleaworlder** [JuliaCI/PkgBenchmark.jl#150]
```julia
    # Tuning
    if isfile(tunefile) && !retune # here
        _benchinfo("using benchmark tuning data in $(abspath(tunefile))")
        BenchmarkTools.loadparams!(suite, BenchmarkTools.load(tunefile)[1], :evals, :samples);
    else
        _benchinfo("creating benchmark tuning file $(abspath(tunefile))...")
        mkpath(dirname(tunefile))
        BenchmarkTools.tune!(suite; runoptions...)
        BenchmarkTools.save(tunefile, params(suite));
    end
```

Tuning always takes up a lot of time, especially in large-scale benchmarks. I'd like to know if there is a way to jump tuning stage? (I hope I didn't misread the corresponding code)

**Comment by filchristou** [comment]
The [docs of BenchmarkTools.jl](https://juliaci.github.io/BenchmarkTools.jl/stable/manual/#Caching-Parameters) suggest to tune once, save to file and then always load the parameters. This helps also for consistency across an updated codebase.

**Comment by filchristou** [comment]
btw, I just tested and it looks like running `PkgBenchmark.benchmarkpkg` generates a `tune.json` file. Rerunning it then, it skips the tunning phase. If you have problems with the CI make sure you check in the file to git.

**Comment by skyleaworlder** [comment]
> btw, I just tested and it looks like running `PkgBenchmark.benchmarkpkg` generates a `tune.json` file. Rerunning it then, it skips the tunning phase. If you have problems with the CI make sure you check in the file to git.

OK, thank you! Finally I exactly did it just like you said.
