### ISSUE TITLE
saving other data

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaCI/PkgBenchmark.jl#17]
First of all awesome package, it is very helpful!

I am not sure if this is appropriate, but I am benchmarking an optimization tool and I am interested in using your tool to not only tell me how long it takes but also the results. For my case, the only other results besides time that I would like to grab are (two numbers) the error and the objective function value. 

Before I started to dig in I was wondering, is this something that I can easily already do? 

**I have another question but I don't think it deserves its own issue:**
1) how many times samples does it have for each run? Is there a way to change this? like in BenchmarkTools?

Thanks!

**Comment by shashi** [comment]
Saving extra data is not possible at the moment. But it would be a good feature to have.

> how many times samples

See
https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#introduction

**Comment by huckl3b3rry87** [comment]
@shashi I was wondering if it would be hard to implement the saving other data thing?

**Comment by KristofferC** [comment]
In my opinion this package should focus on how long time it takes to run functions. Correctness testing and solklar things should be done somewhere else. What's the use case for wanting to combine these?

**Comment by huckl3b3rry87** [comment]
@KristofferC I am trying to benchmark optimization tools. So, I am trying get both the time that it takes to run the problem and then I want to grab some other data that goes along with that run, like a relative error estimate.

**Comment by KristofferC** [comment]
I don't think this is in scope of this package. It has intentionally a quite small API.
