### ISSUE TITLE
Support BenchmarkTools native way of writing benchmark suites

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/PkgBenchmark.jl#18]
The macro based interface to define benchmark suites is a quite small wrapper on top of the "native" one from
BenchmarkTools. Originally, the old BenchmarkTools also used a macro based interface but moved over to the current `Dict` based one, closer matching the internal representation.
From what I have read, the macro based interface had some problems with interpolation, perhaps @jrevels can fill in with some details. Issue #16 is relevant.

As a first step I think at least supporting benchmark suites written using the native `Dict` method is valuable.
I think it can be done with not much extra code, we just need to define a convention for the name of the root benchmarkgroup (perhaps `SUITE`)?

If the macro based interface is too problematic it could be deprecated but that is a later question.

**Comment by shashi** [comment]
> perhaps `SUITE`

sounds good :+1:

**Comment by KristofferC** [comment]
I had to add a register function for the suite into PkgBenchmark. This however means that users still need to require PkgBenchmark to write their tests. Having a naming convention would be better but I had troubles getting access to the `SUITE` variable inside the benchmark file. Have to experiment a bit more...
