### ISSUE TITLE
 No need to throw for dirty repo if the commit we measure is the same as the one we are on.

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/PkgBenchmark.jl#22]
E.g. benchmarking HEAD when the repo is dirty should not error because no checkout is needed. (Note, only when using "HEAD" as an explicit argument).

**Comment by Evizero** [comment]
What error are you observing? I tried benchmarking in a dirty state and things execute fine. The only difference I observe is that the results aren't stored (which I know because of a informative warning message)

**Comment by KristofferC** [comment]
`PkgBenchmark.benchmarkpkg("PkgBenchmark", "HEAD")` fails on a dirty repo.

**Comment by shashi** [comment]
> no checkout is needed

If it's dirty you're not measuring the perf of HEAD itself right? it's HEAD+your dirty stuff. So the alternative is to just run `PkgBenchmark.benchmarkpkg("Package")` maybe the error should say that or something?

wrapping `git stash` and `git stash pop` might be another way to go. We can always successfully run benchmarks then even if the repo is dirty.

**Comment by KristofferC** [comment]
This is true and you are right of course. Stashing and popping might be possible but probably not worth it
