### ISSUE TITLE
Consider storing metadata in the results

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/PkgBenchmark.jl#24]
Right now the results being stored are "naked" `BenchmarkGroup`. I suggest we instead store our own `PkgBenchmarkGroup` object that wraps a `BenchmarkGroup` but where we are free to add arbitrary metadata that can be used for e.g. exporting the results. This could include things like the date and hardware for the benchmark.

**Comment by shashi** [comment]
Nice idea. We could just save 2 `BenchmarkGroup`s in the JLD -- one with the results one with the metadata and mirrors the structure of the results group. `BenchmarkGroup`s can contain anything iiuc. Good to avoid wrapping all operations defined on it.
