### ISSUE TITLE
Rename `judge` parameters

### ISSUE THREAD

**Issue by omus** [JuliaCI/PkgBenchmark.jl#4]
I find that the `to_ref` and `from_ref` parameter names don't tell me much regarding what is being compared. I think the terminology of `baseline` and `candidate` are much clearer in letting the user know that the `candidate` is the new code which is being compared against the `baseline`.

If people like this idea we should probably do the same in BenchmarkTools.jl

**Comment by omus** [comment]
Additionally it looks like `f=(minimum, minimum)` is also outdated and should be changed to `f=minimum`.

**Comment by shashi** [comment]
`f=minimum` is equivalent to `f=(minimum, minimum)` since it will get converted to a repeated tuple if it's not a tuple.
