### ISSUE TITLE
Use the same benchmark suite when judging

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/PkgBenchmark.jl#43]
Currently, when you judge a package between two commits, the benchmarks executed could potentially be different since the file loaded is just the one at the different commits.
I would argue a perhaps better way would be to read in the benchmark suite at the current commit, store that in a file, and use the same benchmark suite for the two commits.

Any opinions @shashi?

**Comment by shashi** [comment]
Yeah, this is a problem. But it might be the case that old benchmarks might not run on the most recent commit... For such situations, you'd have to create a new benchmark file and pass that as `script`.

**Comment by MilesCranmer** [comment]
Sorry if this is already solved, I couldn't find this anywhere.

Could this be automatically inside `benchmarkpkg`?
e.g., the simplest solution, assuming there's no `include`s would be:
```julia
tmp_script = ".pkgbenchmark" * script
cp(script, tmp_script; force=true)
```
at the start of evaluation, and then run on `tmp_script` when comparing to older commits. My guess is it is quite common to compare to older commits, written before the benchmark was created or modified. So it would be nice to have some flag that could set this up automatically.

Thoughts?

Cheers,
Miles
