### ISSUE TITLE
error showing BenchmarkConfig

### ISSUE THREAD

**Issue by Roger-luo** [JuliaCI/PkgBenchmark.jl#78]
It seems the `BenchmarkConfig` prints `nothing` directly?

```julia
current = BenchmarkConfig(id=nothing, env = Dict("JULIA_NUM_THREADS"=>4), juliacmd=`julia -O3`)
```

This print gives an error in REPL.

**Comment by KristofferC** [comment]
https://github.com/JuliaCI/PkgBenchmark.jl/blob/529dbeaa1be4160dfa8824a528fa5b330c5721b1/src/benchmarkconfig.jl#L82 needs to be a `show` or something.
